FROM mysql

# Variables de entorno para el usuario y contraseña
ENV MYSQL_ROOT_PASSWORD=admin1234

# Creamos un volumen para los datos
VOLUME ["/var/lib/mysql"]

# Exponemos el puerto estándar de MySQL
EXPOSE 3306
